### PR TITLE
8287671: Adjust ForceGC to invoke System::gc fewer times for negative case

### PR DESCRIPTION
**Pull request by GoeLin**
A useful test infra improvement. Simplifies backporting changes using ForceGC.

I include build fix 8287867.

Both clean, will mark as clean.

---------
### Progress
- [x] [JDK-8287671](https://bugs.openjdk.org/browse/JDK-8287671) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8287867](https://bugs.openjdk.org/browse/JDK-8287867) needs maintainer approval
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8287671](https://bugs.openjdk.org/browse/JDK-8287671): Adjust ForceGC to invoke System::gc fewer times for negative case (**Bug** - P3 - Approved)
 * [JDK-8287867](https://bugs.openjdk.org/browse/JDK-8287867): Bad merge of jdk/test/lib/util/ForceGC.java causing test compilation error (**Bug** - P1 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-dev.git pull/1860/head:pull/1860` \
`$ git checkout pull/1860`

Update a local copy of the PR: \
`$ git checkout pull/1860` \
`$ git pull https://git.openjdk.org/jdk17u-dev.git pull/1860/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1860`

View PR using the GUI difftool: \
`$ git pr show -t 1860`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-dev/pull/1860.diff">https://git.openjdk.org/jdk17u-dev/pull/1860.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-dev/pull/1860#issuecomment-1752741464)

### CODE REVIEW

**Comment by GoeLin** [comment]
It seems the fact that I added the second issue before the bots had parsed and adapted the title confused either me or the bots.
